### ISSUE TITLE
Authorship, attribution, and roles on posts

### ISSUE THREAD

**Issue by bogovicj** [JaneliaSciComp/JaneliaDataStandards#15]
How explicit do we want to be about how people contributed to posts?
Maybe everyone who contributes is an author? Maybe be explicit about what role everyone took up front?

If we want the latter, I started editing the quarto templates here https://github.com/JaneliaSciComp/JaneliaDataStandards/tree/contributors-reviewers
which would let us do something like this:

![Screenshot from 2024-06-04 09-01-40](https://github.com/JaneliaSciComp/JaneliaDataStandards/assets/6912043/a4bf7487-f3c7-4ed2-ae4d-cbfbebefaa42)

with [this header](https://github.com/JaneliaSciComp/JaneliaDataStandards/commit/324b1b54966b3cbab21c0fd5d412685834994c6a#diff-a860d390355984a703b9c4bf18206d30a3fb110cd7fc9138340be048a99b6941R3-R10)

**Comment by virginiascarlett** [comment]
What did you have in mind for 'contributor'? People who commented but weren't reviewers?

**Comment by bogovicj** [comment]
> What did you have in mind for 'contributor'? People who commented but weren't reviewers?

Yea, I think so (?), but not sure that should be different from "Author". Maybe better not to separate "contributors" from "authors".

I'm tempted to have a list of "endorsers" (or similar) if there are people who want to publicly say "I agree with this".
My thinking here is that it'd be nice for posts to represent the consensus of a group of people and for that fact to be clear

**Comment by mkitti** [comment]
Are we planning to maintain these over time as things change?

Perhaps there a distinct role for a "Maintainer" or "Maintaining Editor". This would be a person who may or may not have had a role in the original article but is currently responsible for the accuracy of the contents?

**Comment by virginiascarlett** [comment]
This might be a conversation more appropriate to my recent PR #14, but it sounds like we're saying each article should have the following attributions?

Author(s) - Wrote the article or made a major modification to the article
Reviewer(s) - Reviewed the article or reviewed a major modification to the article
Contributor(s) - Commented on a draft of the article or provided minor modifications
Maintainer - Party to whom correspondence should be addressed

It might be worth further clarifying the responsibilities of the maintainer, e.g., should they be actively ensuring that the article is still current, or just fielding questions that arise? For instance, I could do the latter, but not the former.

**Comment by virginiascarlett** [comment]
Add endorsers? (Endorsement should be open indefinitely)

**Comment by virginiascarlett** [comment]
Done!
