### ISSUE TITLE
Add disclaimer / notice of work-in-progress

### ISSUE THREAD

**Issue by bogovicj** [JaneliaSciComp/JaneliaDataStandards#4]

**Comment by virginiascarlett** [comment]
Done. Good enough?

**Comment by mkitti** [comment]
It would be useful to note the commit or pull request where the issue was resolved.
https://github.com/JaneliaSciComp/JaneliaDataStandards/commit/9b323d4b47365153872932304b2ceced9f9c660e perhaps?

**Comment by virginiascarlett** [comment]
I'd say the one after it, since I wasn't quite happy with that one. fa351d18ef60a5546721877340cdffd96f7b29c8
Next time I'll link to the issue in the commit message.

**Comment by mkitti** [comment]
If you create a pull request, you can say "Fixes #4". When that pull request gets merged, it will automatically close the corresponding issue with a note of what pull request resolved it.

**Comment by mkitti** [comment]
For example, see this one on ngff 217.
![image](https://github.com/JaneliaSciComp/JaneliaDataStandards/assets/8062771/ce285646-2e3f-4d7d-8c9c-f861d7f23860)
